name: Test and Deploy on Pass

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        env:
          VITE_BACKEND_API_URL: ${{ secrets.VITE_BACKEND_API_URL }}
        run: npm test

      - name: Run backend tests
        working-directory: ./backend
        env:
          VITE_API_URL: ${{ secrets.VITE_BACKEND_API_URL }}
          THIRD_PARTY_GAME_API_URL: ${{ secrets.THIRD_PARTY_GAME_API_URL }}
          THIRD_PARTY_GAME_API_KEY: ${{ secrets.THIRD_PARTY_GAME_API_KEY }}
          FRONTEND_URL_FOR_CORS: ${{ secrets.FRONTEND_URL_FOR_CORS }}
        run: npm test

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.result == 'success'
      
    steps:
      - name: Trigger Frontend Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1j4fa95pdvs73cq4770?key=${{ secrets.FRONTEND_DEPLOY }}

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.result == 'success'
      
    steps:
      - name: Trigger Backend Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1il7lndiees739rlak0?key=${{ secrets.BACKEND_DEPLOY }}
    
